### ISSUE TITLE
toc options

### ISSUE THREAD

**Issue by jonschlinkert** [verbose/verb-toc#4]
@tunnckoCore, here is what I'm thinking for toc options:

``` js
    "toc": {
      "render": true,
      "method": "postLayout",
      "filter": "[*-+]\\s+\\.(\\w)"
    }
```

You'll be able to generate the toc at the specific point in the render cycle (which also adds a toc AST/object to the file object), then inject the toc string when the document is rendered, or you can use a middleware, plugin, or helper to render a custom TOC from the json object.

thoughts?

**Comment by tunnckoCore** [comment]
Yea, sounds good. :+1:

**Comment by jonschlinkert** [comment]
I believe this was all implemented besides `filter`. I'm going to close but we can open a new request for `filter` if that's something you want
